### ISSUE TITLE
Allow ignoring absent properties

### ISSUE THREAD

**Issue by shrralis** [mcarleio/konvert#16]
Is there a way to avoid `io.mcarle.konvert.processor.exceptions.PropertyMappingNotExistingException: No property for...`?

In my case, there's an Entity with a property with a default value:
```kotlin
data class Entity(
    ...
    var something: Boolean = false,
    ...
)
```
and a DTO without the field:
```kotlin
data class DTO(
    ...
    // no `something` field
    ...
)
```

Is there a way to respect the default value declared in the `Entity` constructor?
Having smth like `@Konvert(mappings = [Mapping(target = "something", constant = "false")])` seems **really** redundant

**Comment by mcarleio** [comment]
Thanks for raising this issue! I am sure it once **was** possible.

I fixed it and added a unit test, so that it stays like this :)

**Comment by mcarleio** [comment]
Funny thing: I have just stumbled over my own [documentation](https://github.com/mcarleio/konvert/blob/7abd2efd4680437c64b4b20c759e96013d6ed2e2/annotations/src/main/kotlin/io/mcarle/konvert/api/Mapping.kt#L64) :laughing:

```kotlin
     * * Your source does not have the information for a target with default value
     *    ```kotlin
     *    @KonvertTo(CarToRepair::class, mappings=[
     *         Mapping(target="defect", ignore=true)
     *    ])
     *    class Car
     *    class CarToRepair(val defect: Boolean = true)
     *    ```
``` 

So it was working as expected, I just forgot about that :/
