### ISSUE TITLE
Allow mapping nullable fields to non nullable fields

### ISSUE THREAD

**Issue by b-heimann-senacor** [mcarleio/konvert#18]
It looks like you cannot convert nullable fields to non nullable fields with konvert:

```kotlin
@KonvertTo(Bike::class)
data class BikeDto(val brand: String?)

data class Bike(val brand: String)
```

I would expect konvert to generate a function like this

```kotlin
fun BikeDto.toBike(): Bike =
   Bike(brand = brand!!)
```

At the moment, running `mvn compile` will output this error:

```text
[ERROR] [ksp] java.util.NoSuchElementException: Could not find converter for brand -> brand: String? -> String
```

**Comment by mcarleio** [comment]
You have to configure this (either global or per mapping).
Have a look here: https://mcarleio.github.io/konvert/options/#available-options

> konvert.enforce-not-null

**Comment by b-heimann-senacor** [comment]
This works perfectly fine, thank you!
