### ISSUE TITLE
Allow setting parameters for missing properties

### ISSUE THREAD

**Issue by MV-GH** [mcarleio/konvert#28]
I have a bunch of dtos where I want to pass one of the missing properties through a parameter. 

I thought I could achieve this by doing
```kt
    @Konvert(mappings=[Mapping(target="auth", constant="auth")])
    fun toV0x18(d: v0x19.datatypes.CreateComment, auth: String): CreateComment
``` 

But it throws this error:

```
[ksp] java.lang.IllegalStateException: Konvert annotated function must have exactly one parameter and must have a return type: toV0x18
at io.mcarle.konvert.processor.konvert.KonverterDataCollector$collectKonvertData$1.invoke(KonverterDataCollector.kt:61)
```

So I request the ability to specify missing properties through parameters. This probably a bit complex when generating nested mappings. But I only need it for top level mappings. So sublevel mappings can still throw that error. If it deems to complex. To pass the parameters through nested function calls.

**Comment by mcarleio** [comment]
fixed with 2.4.0
