### ISSUE TITLE
PropertyMappingNotExistingException: No property for valueParameter

### ISSUE THREAD

**Issue by roma2341** [mcarleio/konvert#68]
`[ksp] io.mcarle.konvert.processor.exceptions.PropertyMappingNotExistingException: No property for valueParameter=ownerId existing in [PropertyMappingInfo(mappingParamName=document, sourceName=id, targetName=id, constant=null, expression=null, ignore=false, enableConverters=[], sourceData=SourceProperty(property=id), isBasedOnAnnotation=false), PropertyMappingInfo(mappingParamName=document, sourceName=firstName, targetName=firstName, constant=null, expression=null, ignore=false, enableConverters=[], sourceData=SourceProperty(property=firstName), isBasedOnAnnotation=false), PropertyMappingInfo(mappingParamName=document, sourceName=lastName, targetName=lastName, constant=null, expression=null, ignore=false, enableConverters=[], sourceData=SourceProperty(property=lastName), isBasedOnAnnotation=false), PropertyMappingInfo(mappingParamName=document, sourceName=email, targetName=email, constant=null, expression=null, ignore=false, enableConverters=[], sourceData=SourceProperty(property=email), isBasedOnAnnotation=false), PropertyMappingInfo(mappingParamName=document, sourceName=phone, targetName=phone, constant=null, expression=null, ignore=false, enableConverters=[], sourceData=SourceProperty(property=phone), isBasedOnAnnotation=false)]
`

**Comment by mcarleio** [comment]
Please provide the code to reproduce.

**Comment by roma2341** [comment]
here is:
https://file.io/Jv69cit3a7cO
Try to build user service
