### ISSUE TITLE
Unresolved reference when using KonvertFrom on companion object for nested dtos

### ISSUE THREAD

**Issue by Karkoon** [mcarleio/konvert#75]
Hi. I have this structure:

```kotlin
class GalleryDto(
  val id: UUID,
  val name: String,
  val description: String,
  val images: Map<UUID, ImageDto>
) {
  @KonvertFrom(Gallery::class)
  companion object
}

class ImageDto(
  val id: UUID,
  val name: String,
  val url: URL,
) {
  @KonvertFrom(Image::class)
  companion object
}
````
And the generate code is this:
```kotlin
@GeneratedKonverter(priority = 4_000)
public fun GalleryDto.Companion.fromGallery(gallery: Gallery): GalleryDto = GalleryDto(
  id = gallery.id,
  name = gallery.name,
  description = gallery.description,
  images = gallery.images.mapValues { (_, it) ->
      dev.karkoon.notes.gallery.ImageDto.dev.karkoon.notes.gallery.fromImage(image = it) }
)
```
The line: dev.karkoon.notes.gallery.ImageDto.dev.karkoon.notes.gallery.fromImage(image = it) 
generates an error.

The second "dev" in this line produces an unresolved reference. If I remove the whole second "dev.karkoon.notes.gallery" it works. 

I'm using the 3.2.0 version. Thank you for creating this library.

**Comment by mcarleio** [comment]
Thanks for raising this issue, I could reproduce and implemented a fix. It was a bug in the MapToX converter, where a String was concatenated with a kotlinpoet `CodeBlock` instead of using the `%L` placeholder. With this, the CodeBlock will be converted toString and is unaware of packages, imports, etc.
